### ISSUE TITLE
Als je iets foutiefs hebt ingevoerd, moet je dat eerst weghalen voordat je een nieuwe poging kunt wagen

### ISSUE THREAD

**Issue by PhilipEno** [frankvdg/SMMQ1#21]

**Comment by PhilipEno** [comment]
want alles wat erna getypt wordt, wordt niet herkend

**Comment by frankvdg** [comment]
hij check nu gewoon wat je typt met elk van de woorden uit het antwoord.
mss kan ik ervan maken dat ie wat je typt ook in woorden opsplitst en deze allen checkt met alle woorden van het antwoord. de vraag is dan alleen wat er daarna gebeurd. 
stel ik wil typen: "a horse with no name".
"a" streept ie dan meteen weg en je textarea wordt leeg. 
dan typ ik "hofse", dan gebeurd er niks.
dan typ ik: "hofse with"
dan streept ie "with" weg en blijft "hofse" staan
dan "hofse no name" en blijft alleen "hofse" staan
is dat wat?

anders moeten we toch veranderen naar een enter-systeem

**Comment by frankvdg** [comment]
dit zag je ook vaak bij polle, als je "carley rae jepsen" typt gebeurt er natuurlijk niks. 
is het dan logisch dat "carley" blijft staan en "rae jepsen" in het antwoord vakt komt te staan>?

**Comment by PhilipEno** [comment]
Dat klinkt als een supergoed idee! Anders verlies je ook veel tijd met terug naar het begin gaan en opnieuw typen, terwijl het lekker is als je gewoon door kunt gaan.
Misschien ook een idee - mits mogelijk - dat het tekstvak leeg wordt zodra er een nieuw fragment begint?

**Comment by frankvdg** [comment]
ok dat staat er nu in. 
als je nu "carley rae jepsen" intypt keurt ie "rae jepsen" goed maar blijft "carley" staan.
het probleem met "america a horse with no name" staat nog open

textvlak wordt nu leeg bij nieuw fragment

**Comment by PhilipEno** [comment]
Supernice! Groter lettertype ook slim, speelt lekker zo

**Comment by frankvdg** [comment]
voornu wel acceptabel denk ik
