### ISSUE TITLE
meer nummers toevoegen aan playlist.txt

### ISSUE THREAD

**Issue by frankvdg** [frankvdg/SMMQ1#6]

**Comment by PhilipEno** [comment]
Ik heb nu ergens nummers toegevoegd, en nog een aparte lijst gemaakt met billboard no. 1 hits. Als we iets van playlist keuze mogelijk willen maken, is het dan ook de bedoeling dat we zelf verschillende playlists maken? 
En de playlist aanvulling zoals ik de nu heb gemaakt, is dat goed? Of doe ik nog iets fout?

**Comment by frankvdg** [comment]
ik zie geen playlists en geen toevoegingen, waar is dit?

**Comment by PhilipEno** [comment]
Ik geloof niet dat ik helemaal begrijp hoe dit alles werkt, maar nu heb ik twee keer pull request gedaan, misschien dat je dan wat kunt zien?

**Comment by frankvdg** [comment]
als je op de site edit, hoeft je nooit te pullen of pushen
je kan gewoon hier editten en dan onderin op commit drukken.
pull en push is voor als je andere software gebruikt en je de code op de server wil duwen of eraf halen

**Comment by frankvdg** [comment]
ah ik zie nu dat ik de pull requests kan mergen, dus dan kan ook i guess

**Comment by PhilipEno** [comment]
ah okay, dan ga ik dat volgende keer proberen
